In [2]:
import torch

In [5]:
x = torch.tensor([5.5, 3])
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.4579, -0.9180, -1.9588],
        [ 0.2183, -2.2337, -0.0980],
        [-0.0271, -0.7589, -0.8110],
        [ 0.7848, -1.0307,  0.3717],
        [ 0.3945,  2.9874, -0.7673]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.0847, -0.4805, -1.6767],
        [ 0.3550, -1.7012,  0.7787],
        [ 0.6342, -0.1087, -0.6084],
        [ 1.1314, -0.4042,  0.3813],
        [ 0.7497,  3.6316, -0.7061]])
