# Naive Bayes witk Scikit Learn
## 1. Gaussian Naive Bayes

In [1]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [5]:
x = np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], [-4,0], [-1,1], [1,1], [-2,2], [2,7], [-4,1], [-2,7]])
y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])

In [7]:
#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets 
model.fit(x, y)

#Predict Output 
predicted = model.predict([[1,2],[3,4]])
print(predicted)

[3 4]


## 2. Multinomial Naive Bayes

In [11]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB

In [26]:
x = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [44]:
print(x.shape)
print(x[2])
print("-"*5)
print(x[4])
print("-"*5)
print(y)

(100, 3)
[1 0 1]
-----
[0 1 0]
-----
[1 0 1 1 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 1
 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0
 1 1 0 0 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0]


In [28]:
model = MultinomialNB()

model.fit(x,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
print("for index: %d => real value: %d"%(2, y[2]))
print("for index: %d => predicted value: %d"%(2, model.predict(x[2:3])))

for index: 2 => real value: 3
for index: 2 => predicted value: 3


## 3. Bernoulli Naive Bayes

The Bernoulli naive Bayes classifier assumes that all our features are binary such that they take only two values 

In [55]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

In [56]:
# Create three binary features
x = np.random.randint(2, size=(100, 3))

# Create a binary target vector
y = np.random.randint(2, size=(100, 1))
y = y.ravel()

In [57]:
print(x[2:5])
print("-"*5)
print(y)

[[1 0 1]
 [1 0 0]
 [0 0 0]]
-----
[0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 1 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0
 1 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 0 1 1 1 0 1 1 1 0 0 1 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0]


In [58]:
model = BernoulliNB()
model.fit(x,y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [59]:
print("for index: %d => real value: %d"%(69, y[69]))
print("for index: %d => predicted value: %d"%(69, model.predict(x[69:70])))

for index: 69 => real value: 1
for index: 69 => predicted value: 1


### References
- https://www.analyticsvidhya.com/blog/2017/09/naive-bayes-explained/
- http://scikit-learn.org/stable/modules/naive_bayes.html
- https://chrisalbon.com/machine_learning/naive_bayes/bernoulli_naive_bayes_classifier/
